### ISSUE TITLE
offline suggested companies to add

### ISSUE THREAD

**Issue by balloch** [balloch/awesome-robotics-ai-companies#2]
- [x] Kuka
- [x] Maidbot (Austin)
- [x] Pensa Systems (Austin)

**Comment by balloch** [comment]
- [x] Optimus Ride

**Comment by balloch** [comment]
- [x] Apple Cupertino campus
- [x] Uber Toronto Campus

**Comment by balloch** [comment]
- [x] OSRF (bay area)
- [x] ARL (TX, MD, AL)
- [x] NRL (los angeles, FL, MD, MI, DC)
- [x] NASA JPL (los angeles) & Ames (SF) 
- [x] Honeybee Robotics (NY)
- [x] Nomagic (Warsaw, POL)
- [x] Volocopter (Bruschal, DEU)
- [x] Delta Drone (Lyon, FRA)
- [x] Matternet (bay area)
- [x] Outrider (denver, CO)
- [x] Trifo (bay area)
- [x] Intuition Robotics (Tel aviv israel)
- [x] Measure (Washington D.C.)
- [x] GelSight (Philadelphia)
- [x] Soft Robotics (boston)
- [x] Virtual Incision Corp (Lincoln, NE)
- [x] Bear Robotics (bay area)
- [x] Cafe X (bay area)
- [x] Modular Robotics (Boulder)
- [x] Mapillary (Malmo Sweden)
- [x] Voyage (bay area)

**Comment by bgoldfai** [comment]
The ones I could come up with without diving too deep:

- [x]  Pony.ai (Bay Area)
- [x] Starship (Bay Area)
- [x] Udelv (Bay Area)
- [x] Kodiak (Bay Area)
- [x] Ike (Bay Area)
- [x] Starskey (Bay Area)
- [x] Embark (Bay Area)
- [x] TU Simple (Bay Area)
- [x] JD.com (Bay Area)
- [x] Mercedez Benz (Daimler) (Bay Area) autonomous vehicles
- [x] Bosch (Bay Area)
- [x] Freightliner (Daimler) (Portland)
- [x] PACCAR (Bay Area, Seattle)
- [x] Tesla (Bay Area)
- [x] May Mobility (Ann Arbor)
- [x] Kittyhawk (Bay Area)
- [x] Joby Aviation (Bay Area)
- [x] Cobalt Robotics (Bay Area)
- [x] Farmwise (Bay Area)
- [x] Safe.ai (Bay Area)
- [x] Built Robotics (Bay Area)

Deepscale was acquired by Tesla I believe.

**Comment by balloch** [comment]
Companies from 2020 robot report: https://www.therobotreport.com/robotics-startups-to-watch-2020/ and the new WSJ article: https://www.wsj.com/articles/as-e-commerce-booms-robots-pick-up-human-slack-11596859205

**Comment by balloch** [comment]
- [x] Yaskawa Electric (Japan/Bay Area)

**Comment by balloch** [comment]
- [x] agility robotics

**Comment by balloch** [comment]
Greenzie https://www.greenzie.com/
